version: '3.1'

services:
  node:
    container_name: nodetube
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "49161:3000"
    volumes:
      - /app/node_modules
      - ./upload:/app/upload
      - ./uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://nodetube-mongo:27017/nodetube
    depends_on:
      - redis
      - mongo
    command: npm start
    networks:
      - nodetube-network

  mongo:
    container_name: nodetube-mongo
    image: mongo:3.6
    volumes:
      - ./data/db:/data/db
    ports:
      - "27011:27017"
    networks:
      - nodetube-network

  redis:
    container_name: nodetube-redis
    image: redis
    networks:
      - nodetube-network

networks:
  nodetube-network:
    driver: bridge
